const User = require('../models/User');

// @desc    Create a new sub-admin
// @route   POST /api/subadmins
// @access  Private/SuperAdmin
exports.createSubAdmin = async (req, res) => {
  try {
    const { name, email, contactNo, password, transactionPassword, permissions } = req.body;

    const userExists = await User.findOne({ $or: [{ email }, { contactNo }] });
    if (userExists) {
      return res.status(400).json({ message: 'User with this email or contact number already exists' });
    }

    const subAdmin = await User.create({
      name,
      email,
      contactNo,
      password,
      transactionPassword,
      role: 'admin',
      adminType: 'SUB_ADMIN',
      permissions: permissions || [],
      accountStatus: 'ACTIVE',
      // memberId is automatically generated by pre-save hook in User model
    });

    res.status(201).json({
      _id: subAdmin._id,
      name: subAdmin.name,
      email: subAdmin.email,
      memberId: subAdmin.memberId,
      permissions: subAdmin.permissions
    });
  } catch (error) {
    console.error('Error creating sub-admin:', error);
    res.status(500).json({ message: 'Server Error', error: error.message });
  }
};

// @desc    Get all sub-admins
// @route   GET /api/subadmins
// @access  Private/SuperAdmin
exports.getSubAdmins = async (req, res) => {
  try {
    const subAdmins = await User.find({ role: 'admin', adminType: 'SUB_ADMIN' })
      .select('-password -transactionPassword -plainPassword -plainTransactionPassword')
      .sort({ createdAt: -1 });
    res.status(200).json(subAdmins);
  } catch (error) {
    console.error('Error fetching sub-admins:', error);
    res.status(500).json({ message: 'Server Error', error: error.message });
  }
};

// @desc    Update sub-admin
// @route   PUT /api/subadmins/:id
// @access  Private/SuperAdmin
exports.updateSubAdmin = async (req, res) => {
  try {
    const { name, email, contactNo, password, transactionPassword, permissions, accountStatus } = req.body;

    const subAdmin = await User.findOne({ _id: req.params.id, role: 'admin', adminType: 'SUB_ADMIN' });

    if (!subAdmin) {
      return res.status(404).json({ message: 'Sub-admin not found' });
    }

    if (name) subAdmin.name = name;
    if (email) subAdmin.email = email;
    if (contactNo) subAdmin.contactNo = contactNo;
    if (permissions) subAdmin.permissions = permissions;
    if (accountStatus) subAdmin.accountStatus = accountStatus;
    
    // Only update passwords if provided
    if (password) subAdmin.password = password;
    if (transactionPassword) subAdmin.transactionPassword = transactionPassword;

    await subAdmin.save();

    res.status(200).json({
      _id: subAdmin._id,
      name: subAdmin.name,
      email: subAdmin.email,
      memberId: subAdmin.memberId,
      permissions: subAdmin.permissions,
      accountStatus: subAdmin.accountStatus
    });
  } catch (error) {
    console.error('Error updating sub-admin:', error);
    res.status(500).json({ message: 'Server Error', error: error.message });
  }
};
