import { useCallback, useEffect, useMemo, useState } from 'react';
import { getEpinList, updateEpinStatus, transferEpin, getEpinTransferHistory } from '../../api/managementService';

const statusClass = (status) => {
  if (status === 'Used') return 'epin-chip-used';
  if (status === 'Deleted') return 'epin-chip-deleted';
  return 'epin-chip-unused';
};

export default function EpinTablePage({ title, heading, statusFilter, mode, showActions = true }) {
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [pageSize, setPageSize] = useState('10');
  const [filters, setFilters] = useState({ epin: '', generatedBy: '', currentOwner: '', memberId: '', fromDate: '', toDate: '' });

  const loadRows = useCallback(async () => {
    try {
      if (mode === 'transfer-history') {
        const response = await getEpinTransferHistory();
        setRows(response.transfers || []);
        return;
      }
      const response = await getEpinList(statusFilter ? { status: statusFilter } : {});
      setRows(response.epins || []);
    } catch (error) {
      setRows([]);
    } finally {
      setLoading(false);
    }
  }, [mode, statusFilter]);

  useEffect(() => { loadRows(); }, [loadRows]);

  const filteredRows = useMemo(() => {
    return rows.filter((row) => {
      if (mode === 'transfer-history') {
        return true;
      }
      const matchesEpin = !filters.epin || String(row.epin || '').toLowerCase().includes(filters.epin.toLowerCase());
      const matchesGeneratedBy = !filters.generatedBy || String(row.genBy || '').toLowerCase().includes(filters.generatedBy.toLowerCase());
      const matchesCurrentOwner = !filters.currentOwner || String(row.currentOwner || '').toLowerCase().includes(filters.currentOwner.toLowerCase());
      return matchesEpin && matchesGeneratedBy && matchesCurrentOwner;
    });
  }, [filters, rows, mode]);

  const visibleRows = filteredRows.slice(0, Number(pageSize));
  const isTransferHistory = mode === 'transfer-history';

  const handleAction = async (epinNo, action) => {
    if (action === 'delete') {
      await updateEpinStatus(epinNo, { status: 'Deleted' });
    }
    if (action === 'use') {
      await updateEpinStatus(epinNo, { status: 'Used', usedBy: 'MEMBER', usedDate: new Date().toLocaleString('en-IN') });
    }
    if (action === 'transfer') {
      await transferEpin(epinNo, { toMember: 'MEMBER' });
    }
    await loadRows();
  };

  return (
    <div>
      <h1 className="page-title">{title}</h1>
      <div className="panel">
        <div className="epin-header-row"><h2 className="epin-title">{heading}</h2></div>
        <div className="epin-filter-grid">
          <input className="text-input" placeholder="ePin" value={filters.epin} onChange={(event) => setFilters((prev) => ({ ...prev, epin: event.target.value }))} />
          <input className="text-input" placeholder="Generated By" value={filters.generatedBy} onChange={(event) => setFilters((prev) => ({ ...prev, generatedBy: event.target.value }))} />
          <input className="text-input" placeholder="Current Owner" value={filters.currentOwner} onChange={(event) => setFilters((prev) => ({ ...prev, currentOwner: event.target.value }))} />
          <input className="text-input" type="date" />
          <input className="text-input" type="date" />
          <select className="select-input" value={pageSize} onChange={(event) => setPageSize(event.target.value)}><option value="10">10</option><option value="25">25</option><option value="50">50</option></select>
          <button className="btn-primary" type="button" onClick={loadRows}>Search</button>
        </div>
        <div className="table-wrap">
          <table className="data-table">
            <thead>
              {isTransferHistory ? (
                <tr>
                  <th>#</th><th>Transfer Date</th><th>ePin</th><th>From Member</th><th>To Member</th><th>Amount</th><th>Status</th>
                </tr>
              ) : (
                <tr>
                  <th>#</th><th>ePinName</th><th>ePin</th><th>Cost</th><th>Gen. Date</th><th>Gen. By</th><th>Cur.Owner</th><th>Status</th><th>Used By</th><th>Used Date</th><th>Action</th>
                </tr>
              )}
            </thead>
            <tbody>
              {loading ? (
                <tr><td colSpan={isTransferHistory ? 7 : 11}>Loading...</td></tr>
              ) : visibleRows.length ? visibleRows.map((row, index) => (
                isTransferHistory ? (
                  <tr key={row.epin || row.id}>
                    <td>{index + 1}</td>
                    <td>{row.transferDate}</td>
                    <td>{row.epin}</td>
                    <td>{row.fromMember}</td>
                    <td>{row.toMember}</td>
                    <td>{row.amount}</td>
                    <td><span className={`epin-chip ${statusClass(row.status)}`}>{row.status}</span></td>
                  </tr>
                ) : (
                  <tr key={row.epin || row.id}>
                    <td>{index + 1}</td>
                    <td>{row.epinName}</td>
                    <td>{row.epin}</td>
                    <td>{row.cost}</td>
                    <td>{row.genDate || row.transferDate}</td>
                    <td>{row.genBy || row.fromMember}</td>
                    <td>{row.currentOwner || row.toMember}</td>
                    <td><span className={`epin-chip ${statusClass(row.status)}`}>{row.status}</span></td>
                    <td>{row.usedBy || row.fromMember || '-'}</td>
                    <td>{row.usedDate || row.transferDate || '-'}</td>
                    <td>
                      {showActions ? (
                        <>
                          <button type="button" className="epin-delete-btn" onClick={() => handleAction(row.epin, 'delete')}>x</button>
                        </>
                      ) : '-'}
                    </td>
                  </tr>
                )
              )) : (
                <tr><td colSpan={isTransferHistory ? 7 : 11}>No Record Found</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}